---
- name: Deploy SKMZ app
  hosts: webserver
  become: yes

  tasks:
    # Clone the GitHub repository
    - name: Clone GitHub repository
      git:
        repo: https://github.com/Hsouna20/skmz.git
        dest: /home/hsounaa/skmz
        clone: yes
        force: yes

    # Install Docker and Docker Compose
    - name: Install Docker and Docker Compose
      apt:
        name:
          - docker.io
          - docker-compose
        state: present
    
    
    # Build and start the app with docker-compose
    - name: Build and start app with docker-compose
      docker_compose:
        project_name: skmz
        pull: yes
        build: yes
        build_args:
          - NODE_ENV=production
        state: started
        recreate: yes
        files:
          - /home/hsouna/skmz/docker-compose.yml
