---
- name: Configure API server and frontend
  hosts: webserver
  become: true
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '<hsounaa> ALL=(ALL) NOPASSWD:ALL'

  tasks:
    - name: Install required packages
      apt:
        name:
          - git
          - golang
          - nodejs
          - npm
        state: present

    - name: Clone API server repository
      git:
        repo: https://github.com/Hsouna20/skmz.git
        dest: /opt/my-api
        version: main

    - name: Build API server
      command: go build
      args:
        chdir: /opt/my-api

    - name: Start API server
      command: ./my-api
      args:
        chdir: /opt/my-api
      async: 30
      poll: 5
      register: api_server_pid
      changed_when: false

    - name: Clone frontend repository
      git:
        repo: https://github.com/Hsouna20/skmz.git
        dest: /var/www/html
        version: main

    - name: Install frontend dependencies
      npm:
        path: /var/www/html
        state: present

    - name: Configure Nginx
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify:
        - Reload Nginx

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: restarted

    - name: Stop API server
      command: kill {{ api_server_pid.pid }}
      when: api_server_pid is defined and api_server_pid.returncode is not defined
