---
- name: Deploy HSOUNA2 app using Docker Compose
  hosts: webserver
  become: true
  vars:
    docker_registry: "hsouna2/skmz-first-try"
    app_name: "skmz-first-try"
    app_version: "1.0"
  tasks:
    
    - name: Install Docker
      apt:
        name: docker.io
        state: present
    - name: Log in to Docker Hub
      docker_login:
        username: "hsouna2"
        password: "Has+Sah2025@#"

    - name: Download Docker Compose file from GitHub
      get_url:
        url: "https://raw.githubusercontent.com/hsouna/skmz/docker-compose.yml"
        dest: "docker-compose.yml"
    - name: Pull Docker image from Docker Hub
      docker_image:
        name: "{{ docker_registry }}:{{ app_version }}"
        source: pull
    - name: Deploy the app using Docker Compose
      command: "docker-compose up -d"
      args:
        chdir: "{{ playbook_dir }}"
