---
- name: Configure API server and frontend
  hosts: webserver
  become: true

  tasks:
    - name: Install required packages
      apt:
        name:
          - git
          - golang
          - nodejs
          - npm
        state: present

    - name: Clone API server repository
      git:
        repo: https://github.com/Hsouna20/skmz
        dest: /opt/my-api
        version: main

    - name: Build API server
      command: go build -o my-api
      args:
        chdir: /opt/my-api

    - name: Start API server
      command: ./my-api
      args:
        chdir: /opt/my-api
      async: 30
      poll: 5
      register: api_server_pid
      changed_when: false

    - name: Clone frontend repository
      git:
        repo: https://github.com/Hsouna20/skmz
       
