---
- name: create a symlink
  hosts: all
  vars:
    mysrc: "/etc/ansible/ansible.cfg"
    mylink: "~/.git"
  tasks:
    - name: Creating a symlink
      ansible.builtin.file:
        src: "{{ mysrc }}"
        dest: "{{ mylink }}"
        state: link
